### PR TITLE
Fix intermittent test failure due to any? DSL

### LINKED ISSUE #1974: any? DSL raises "ArgumentError: wrong number of arguments"
```
Failures:

  1) Capistrano::DSL checking for presence variable exists, is not an array 
     Failure/Error:
       def any?(key)
         value = fetch(key)
         if value && value.respond_to?(:any?) && value.method(:any?).arity < 1
           value.any?
         else
           !fetch(key).nil?

     ArgumentError:
       wrong number of arguments (given 0, expected 1)
     # ./lib/capistrano/configuration.rb:47:in `any?'
     # ./lib/capistrano/configuration.rb:50:in `any?'
     # ./spec/integration/dsl_spec.rb:386:in `block (3 levels) in <top (required)>'
     # ./spec/integration/dsl_spec.rb:405:in `block (4 levels) in <top (required)>'
```

This seems to be a test ordering issue.

Using Ruby 2.4.3, I can consistently reproduce using the following seed:

```
$ bundle exec rspec --seed 50238
```

### PR DESCRIPTION
**Pull request by mattbrictson**
Capistrano's `any?` DSL method, as a convenience, will delegate a zero-
arity call to `any?` for the object stored in the variable that is being
interrogated. For example, `any?(:ssh_options)` will first fetch the
value of the variable `:ssh_options`, and then call `any?` on it with
zero arguments.

The bug stems from the fact that we were not checking the arity of
`any?` before calling it. So if the object being interrogated has an
`any?` method that requires an argument, the method invocation will fail
with an `ArgumentError`.

For whatever reason, under certain circumstances related to test order,
the stub object provided by Rspec would sometimes have an `any?` method
on it (inherited from `Capistrano::DSL`) that required an argument.
Hence we would occasionally see test failures.

~~This commit fixes the bug by checking the arity of `any?` before calling
it.~~

There isn't a reliable way to check the arity of `any?` (it is `-1` for
forwarded or native methods), so the fix is to simply rescue the
`ArgumentError` and fallback to non-`any?` behavior.

Fixes #1974

### Short checklist

- [x] Did you run `bundle exec rubocop -a` to fix linter issues?
- [x] Did you confirm that the RSpec tests pass?

### CODE REVIEW

**Comment by mattbrictson** [comment]
This PR is incomplete, because `Array.new.method(:any?).arity` is `-1`, not `0`, on Ruby 2.5.1.

**Comment by mattbrictson** [comment]
Fixed

File: lib/capistrano/configuration.rb [hunk 1]
```diff
@@ -47,10 +47,14 @@ def remove(key, *values)
     def any?(key)
       value = fetch(key)
       if value && value.respond_to?(:any?)
```
Comment (will-in-wi) [inline lib/capistrano/configuration.rb]: Would `value.method(:any?).parameters == []` be a better way of handling this instead of the rescue? Lighter-weight and only saves us from the specific case we care about.

Also, is there any way to write a reliable test for both cases?

**Comment by will-in-wi** [comment]
As a general thought, have we tried using `rspec --bisect` with a failing seed? If we grab the specific seed that fails, does it fail consistently?

**Comment by will-in-wi** [comment]
Sorry, I'm jumping in without full context. I see that you have found a failing seed here: https://github.com/capistrano/capistrano/issues/1974. Does `--bisect` help on that seed?

File: lib/capistrano/configuration.rb (hunk 1 above)
Comment (mattbrictson) [reply lib/capistrano/configuration.rb]: > `value.method(:any?).parameters == []`

That doesn't work for `Array#any?` in Ruby 2.5.1:

```
>> [].method(:any?).parameters
[
    [0] [
        [0] :rest
    ]
]
```

And it gives a different result for forwarded methods:

```
>> class Foo
>>   extend Forwardable
>>   def_delegators :@array, :any?
>> 
>>   def initialize
>>     @array = []
>>   end
>> end
:initialize
>> Foo.new.method(:any?).parameters
[
    [0] [
        [0] :rest,
        [1] :args
    ],
    [1] [
        [0] :block,
        [1] :block
    ]
]
```

So basically we can't trust `arity` or `parameters`. 😄

Comment (mattbrictson) [reply lib/capistrano/configuration.rb]: > Also, is there any way to write a reliable test for both cases?

Yes, I can rewrite the test so that it does not use `stub` (which makes it inconsistent based on the mocha version).
